name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        java: [17-ubuntu]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - uses: gradle/actions/wrapper-validation@v4
      - run: ./gradlew check build --stacktrace
      - uses: actions/upload-artifact@v4
        with:
          name: Artifacts ${{ matrix.java }}
          path: |
            build/libs/
            ./*/build/libs/

